# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/toshiba/folio100/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/toshiba/folio100/proprietary/libaudio.so:obj/lib/libaudio.so \
    vendor/toshiba/folio100/proprietary/libaudiopolicy.so:obj/lib/libaudiopolicy.so \
    vendor/toshiba/folio100/proprietary/libnvrm_graphics.so:obj/lib/libnvrm_graphics.so \
    vendor/toshiba/folio100/proprietary/libnvddk_audiofx.so:obj/lib/libnvddk_audiofx.so \
    vendor/toshiba/folio100/proprietary/libnvodm_query.so:obj/lib/libnvodm_query.so \
    vendor/toshiba/folio100/proprietary/libnvodm_misc.so:obj/lib/libnvodm_misc.so \
    vendor/toshiba/folio100/proprietary/libnvrm.so:obj/lib/libnvrm.so \
    vendor/toshiba/folio100/proprietary/libnvos.so:obj/lib/libnvos.so \
    vendor/toshiba/folio100/proprietary/libnvdispmgr_d.so:obj/lib/libnvdispmgr_d.so \
    vendor/toshiba/folio100/proprietary/libnvdispatch_helper.so:obj/lib/libnvdispatch_helper.so \
    vendor/toshiba/folio100/proprietary/libnvomxilclient.so:obj/lib/libnvomxilclient.so \
    vendor/toshiba/folio100/proprietary/libhwmediarecorder.so:obj/lib/libhwmediarecorder.so

# Standard blobs necessary for folio100
PRODUCT_COPY_FILES += \
    vendor/toshiba/folio100/proprietary/libaudio.so:system/lib/libaudio.so \
    vendor/toshiba/folio100/proprietary/libcamera.so:system/lib/libnvcamera.so \
    vendor/toshiba/folio100/proprietary/libcgdrv.so:system/lib/libcgdrv.so \
    vendor/toshiba/folio100/proprietary/gles2_sanity.so:system/lib/gles2_sanity.so \
    vendor/toshiba/folio100/proprietary/gles2_simplespin.so:system/lib/gles2_simplespin.so \
    vendor/toshiba/folio100/proprietary/libopencorehw.so:system/lib/libopencorehw.so \
    vendor/toshiba/folio100/proprietary/omxplayer.so:system/lib/omxplayer.so \
    vendor/toshiba/folio100/proprietary/libhwmediarecorder.so:system/lib/libhwmediarecorder.so \
    vendor/toshiba/folio100/proprietary/libhwmediaplugin.so:system/lib/libhwmediaplugin.so

# toshiba blobs for folio100
PRODUCT_COPY_FILES += \
    vendor/toshiba/folio100/proprietary/libnvodm_dtvtuner.so:system/lib/libnvodm_dtvtuner.so \
    vendor/toshiba/folio100/proprietary/libnvsm.so:system/lib/libnvsm.so \
    vendor/toshiba/folio100/proprietary/libnvddk_2d_v2.so:system/lib/libnvddk_2d_v2.so \
    vendor/toshiba/folio100/proprietary/libnvmm_utils.so:system/lib/libnvmm_utils.so \
    vendor/toshiba/folio100/proprietary/libnvomxilclient.so:system/lib/libnvomxilclient.so \
    vendor/toshiba/folio100/proprietary/libnvmm_video.so:system/lib/libnvmm_video.so \
    vendor/toshiba/folio100/proprietary/libnvrm_channel.so:system/lib/libnvrm_channel.so \
    vendor/toshiba/folio100/proprietary/libnvmm_camera.so:system/lib/libnvmm_camera.so \
    vendor/toshiba/folio100/proprietary/libnvdispatch_helper.so:system/lib/libnvdispatch_helper.so \
    vendor/toshiba/folio100/proprietary/libnvmm_misc.so:system/lib/libnvmm_misc.so \
    vendor/toshiba/folio100/proprietary/libnvmm_contentpipe.so:system/lib/libnvmm_contentpipe.so \
    vendor/toshiba/folio100/proprietary/libnvodm_misc.so:system/lib/libnvodm_misc.so \
    vendor/toshiba/folio100/proprietary/libnvmm_tracklist.so:system/lib/libnvmm_tracklist.so \
    vendor/toshiba/folio100/proprietary/libnvtestresults.so:system/lib/libnvtestresults.so \
    vendor/toshiba/folio100/proprietary/libnvapputil.so:system/lib/libnvapputil.so \
    vendor/toshiba/folio100/proprietary/libnvmm_service.so:system/lib/libnvmm_service.so \
    vendor/toshiba/folio100/proprietary/libnvodm_hdmi.so:system/lib/libnvodm_hdmi.so \
    vendor/toshiba/folio100/proprietary/libnvodm_imager.so:system/lib/libnvodm_imager.so \
    vendor/toshiba/folio100/proprietary/libnvidia_graphics_jni.so:system/lib/libnvidia_graphics_jni.so \
    vendor/toshiba/folio100/proprietary/libnvodm_query.so:system/lib/libnvodm_query.so \
    vendor/toshiba/folio100/proprietary/libnvidia_display_jni.so:system/lib/libnvidia_display_jni.so \
    vendor/toshiba/folio100/proprietary/libnvwsi.so:system/lib/libnvwsi.so \
    vendor/toshiba/folio100/proprietary/libnvmm_image.so:system/lib/libnvmm_image.so \
    vendor/toshiba/folio100/proprietary/libnvmm_vp6_video.so:system/lib/libnvmm_vp6_video.so \
    vendor/toshiba/folio100/proprietary/libnvdispmgr_d.so:system/lib/libnvdispmgr_d.so \
    vendor/toshiba/folio100/proprietary/libnvmm.so:system/lib/libnvmm.so \
    vendor/toshiba/folio100/proprietary/libnvmm_parser.so:system/lib/libnvmm_parser.so \
    vendor/toshiba/folio100/proprietary/libnvomx.so:system/lib/libnvomx.so \
    vendor/toshiba/folio100/proprietary/libnvos.so:system/lib/libnvos.so \
    vendor/toshiba/folio100/proprietary/libnvddk_audiofx.so:system/lib/libnvddk_audiofx.so \
    vendor/toshiba/folio100/proprietary/libnvddk_2d.so:system/lib/libnvddk_2d.so \
    vendor/toshiba/folio100/proprietary/libnvrm_graphics.so:system/lib/libnvrm_graphics.so \
    vendor/toshiba/folio100/proprietary/libnvwinsys.so:system/lib/libnvwinsys.so \
    vendor/toshiba/folio100/proprietary/libnvrm.so:system/lib/libnvrm.so \
    vendor/toshiba/folio100/proprietary/libnvmm_manager.so:system/lib/libnvmm_manager.so \
    vendor/toshiba/folio100/proprietary/libnvddk_aes_user.so:system/lib/libnvddk_aes_user.so \
    vendor/toshiba/folio100/proprietary/libnvtestio.so:system/lib/libnvtestio.so \
    vendor/toshiba/folio100/proprietary/libnvmm_writer.so:system/lib/libnvmm_writer.so \
    vendor/toshiba/folio100/proprietary/libnvmm_videorenderer.so:system/lib/libnvmm_videorenderer.so \
    vendor/toshiba/folio100/proprietary/libnvmm_audio.so:system/lib/libnvmm_audio.so \
    vendor/toshiba/folio100/proprietary/libnvec.so:system/lib/libnvec.so \
    vendor/toshiba/folio100/proprietary/libpvnvomx.so:system/lib/libpvnvomx.so \
    vendor/toshiba/folio100/proprietary/pvnvomx.cfg:system/etc/pvnvomx.cfg \
    vendor/toshiba/folio100/proprietary/nvmm_jpegenc_test.so:system/lib/nvmm_jpegenc_test.so \
    vendor/toshiba/folio100/proprietary/nvec_update_app.so:system/lib/nvec_update_app.so \
    vendor/toshiba/folio100/proprietary/nvmm_videodec_test.so:system/lib/nvmm_videodec_test.so \
    vendor/toshiba/folio100/proprietary/nvodm_imager_conformance.so:system/lib/nvodm_imager_conformance.so \
    vendor/toshiba/folio100/proprietary/nvmm_videoenc_test.so:system/lib/nvmm_videoenc_test.so \
    vendor/toshiba/folio100/proprietary/nvddk_2d_test_sanity.so:system/lib/nvddk_2d_test_sanity.so \
    vendor/toshiba/folio100/proprietary/nvodm_focuser_conformance.so:system/lib/nvodm_focuser_conformance.so

# nvidia framework files for folio100
PRODUCT_COPY_FILES += \
    vendor/toshiba/folio100/proprietary/com.nvidia.display.jar:system/framework/com.nvidia.display.jar \
    vendor/toshiba/folio100/proprietary/com.nvidia.graphics.jar:system/framework/com.nvidia.graphics.jar

# EGL files for folio100
PRODUCT_COPY_FILES += \
    vendor/toshiba/folio100/proprietary/libEGL_tegra.so:system/lib/egl/libEGL_tegra.so \
    vendor/toshiba/folio100/proprietary/libGLESv1_CM_tegra.so:system/lib/egl/libGLESv1_CM_tegra.so \
    vendor/toshiba/folio100/proprietary/libGLESv2_tegra.so:system/lib/egl/libGLESv2_tegra.so

# Permission files for folio100
PRODUCT_COPY_FILES += \
    vendor/toshiba/folio100/proprietary/com.nvidia.display.xml:/system/etc/permissions/com.nvidia.display.xml \
    vendor/toshiba/folio100/proprietary/com.nvidia.graphics.xml:/system/etc/permissions/com.nvidia.graphics.xml

# HW libs for folio100
PRODUCT_COPY_FILES += \
    vendor/toshiba/folio100/proprietary/gralloc.tegra.so:system/lib/hw/gralloc.tegra.so \
    vendor/toshiba/folio100/proprietary/overlay.tegra.so:system/lib/hw/overlay.tegra.so \
    vendor/toshiba/folio100/proprietary/lights.tegra.so:system/lib/hw/lights.tegra.so \
    vendor/toshiba/folio100/proprietary/sensors.tegra.so:system/lib/hw/sensors.tegra.so \
    vendor/toshiba/folio100/proprietary/hdmi.tegra.so:system/lib/hw/hdmi.tegra.so \
    vendor/toshiba/folio100/proprietary/dmi.tegra.so:system/lib/hw/dmi.tegra.so

# Keychar files for folio100
PRODUCT_COPY_FILES += \
    vendor/toshiba/folio100/proprietary/nvec_keyboard.kcm.bin:system/usr/keychars/nvec_keyboard.kcm.bin \
    vendor/toshiba/folio100/proprietary/usb_keyboard_102_en_us.kcm.bin:system/usr/keychars/usb_keyboard_102_en_us.kcm.bin \
    vendor/toshiba/folio100/proprietary/tegra-kbc.kcm.bin:system/usr/keychars/tegra-kbc.kcm.bin \
    vendor/toshiba/folio100/proprietary/gpio-keys.kcm.bin:system/usr/keychars/gpio-keys.kcm.bin

# Keylayout files for folio100
PRODUCT_COPY_FILES += \
    vendor/toshiba/folio100/proprietary/gpio-keys.kl:system/usr/keychars/gpio-keys.kl \
    vendor/toshiba/folio100/proprietary/nvec_keyboard.kl:system/usr/keychars/nvec_keyboard.kl \
    vendor/toshiba/folio100/proprietary/tegra-kbc.kl:system/usr/keychars/tegra-kbc.kl \
    vendor/toshiba/folio100/proprietary/usb_keyboard_102_en_us.kl:system/usr/keychars/usb_keyboard_102_en_us.kl

# bin files for folio100
PRODUCT_COPY_FILES += \
    vendor/toshiba/folio100/proprietary/nvmm_vc1dec.axf:system/bin/nvmm_vc1dec.axf \
    vendor/toshiba/folio100/proprietary/nvmm_wmaprodec.axf:system/bin/nvmm_wmaprodec.axf \
    vendor/toshiba/folio100/proprietary/nvmm_h264dec.axf:system/bin/nvmm_h264dec.axf \
    vendor/toshiba/folio100/proprietary/nvmm_service.axf:system/bin/nvmm_service.axf \
    vendor/toshiba/folio100/proprietary/nvmm_adtsdec.axf:system/bin/nvmm_adtsdec.axf \
    vendor/toshiba/folio100/proprietary/nvmm_wavdec.axf:system/bin/nvmm_wavdec.axf \
    vendor/toshiba/folio100/proprietary/nvmm_reference.axf:system/bin/nvmm_reference.axf \
    vendor/toshiba/folio100/proprietary/nv_hciattach:system/bin/nv_hciattach \
    vendor/toshiba/folio100/proprietary/nvmm_sorensondec.axf:system/bin/nvmm_sorensondec.axf \
    vendor/toshiba/folio100/proprietary/nvmm_mp3dec.axf:system/bin/nvmm_mp3dec.axf \
    vendor/toshiba/folio100/proprietary/nvddk_audiofx_core.axf:system/bin/nvddk_audiofx_core.axf \
    vendor/toshiba/folio100/proprietary/nvmm_sw_mp3dec.axf:system/bin/nvmm_sw_mp3dec.axf \
    vendor/toshiba/folio100/proprietary/nvmm_aacdec.axf:system/bin/nvmm_aacdec.axf \
    vendor/toshiba/folio100/proprietary/nvrm_daemon:system/bin/nvrm_daemon \
    vendor/toshiba/folio100/proprietary/nvmm_jpegenc.axf:system/bin/nvmm_jpegenc.axf \
    vendor/toshiba/folio100/proprietary/nvdmmultidisplay:system/bin/nvdmmultidisplay \
    vendor/toshiba/folio100/proprietary/nvddk_audiofx_transport.axf:system/bin/nvddk_audiofx_transport.axf \
    vendor/toshiba/folio100/proprietary/nvmm_mp2dec.axf:system/bin/nvmm_mp2dec.axf \
    vendor/toshiba/folio100/proprietary/nvtest:system/bin/nvtest \
    vendor/toshiba/folio100/proprietary/nvmm_mpeg4dec.axf:system/bin/nvmm_mpeg4dec.axf \
    vendor/toshiba/folio100/proprietary/nvmm_wmadec.axf:system/bin/nvmm_wmadec.axf \
    vendor/toshiba/folio100/proprietary/nvmm_audiomixer.axf:system/bin/nvmm_audiomixer.axf \
    vendor/toshiba/folio100/proprietary/nvmm_manager.axf:system/bin/nvmm_manager.axf \
    vendor/toshiba/folio100/proprietary/nvmm_jpegdec.axf:system/bin/nvmm_jpegdec.axf \
    vendor/toshiba/folio100/proprietary/nvrm_avp.axf:system/bin/nvrm_avp.axf \
    vendor/toshiba/folio100/proprietary/tegrastats:system/bin/tegrastats

# wifi/bt files for folio100
#PRODUCT_COPY_FILES += \
#    vendor/toshiba/folio100/proprietary/bluecore6.psr:system/etc/bluez/bluecore6.psr \
#    vendor/toshiba/folio100/proprietary/fw_bcm4329.bin:system/lib/hw/wlan/fw_bcm4329.bin \
#    vendor/toshiba/folio100/proprietary/BCM4329B1.hcd:system/lib/hw/wlan/BCM4329B1.hcd \
#    vendor/toshiba/folio100/proprietary/nvram.txt:system/lib/hw/wlan/nvram.txt \
#    vendor/toshiba/folio100/proprietary/fw_bcm4329_apsta.bin:system/lib/hw/wlan/fw_bcm4329_apsta.bin \
#    vendor/toshiba/folio100/proprietary/bc_hciattach:system/bin/bc_hciattach
#EOF

PRODUCT_COPY_FILES += \
    vendor/toshiba/folio100/proprietary/wmiconfig:system/bin/wmiconfig \
    vendor/toshiba/folio100/proprietary/hostapd_wps:system/bin/hostapd_wps \
    vendor/toshiba/folio100/proprietary/hostapd:system/bin/hostapd \
    vendor/toshiba/folio100/proprietary/hostapd_cli:system/bin/hostapd_cli \
    vendor/toshiba/folio100/proprietary/hostapd.conf:system/etc/hostapd.conf 

PRODUCT_COPY_FILES += \
    vendor/toshiba/folio100/proprietary/akmd8975:system/bin/akmd8975

# OMX libs for folio100
PRODUCT_COPY_FILES += \
    vendor/toshiba/folio100/proprietary/libomx_aacdec_sharedlibrary.so:system/lib/libomx_aacdec_sharedlibrary.so \
    vendor/toshiba/folio100/proprietary/libomx_amrdec_sharedlibrary.so:system/lib/libomx_amrdec_sharedlibrary.so \
    vendor/toshiba/folio100/proprietary/libomx_amrenc_sharedlibrary.so:system/lib/libomx_amrenc_sharedlibrary.so \
    vendor/toshiba/folio100/proprietary/libomx_avcdec_sharedlibrary.so:system/lib/libomx_avcdec_sharedlibrary.so \
    vendor/toshiba/folio100/proprietary/libomx_m4vdec_sharedlibrary.so:system/lib/libomx_m4vdec_sharedlibrary.so \
    vendor/toshiba/folio100/proprietary/libomx_mp3dec_sharedlibrary.so:system/lib/libomx_mp3dec_sharedlibrary.so \
    vendor/toshiba/folio100/proprietary/libomx_sharedlibrary.so:system/lib/libomx_sharedlibrary.so \
    vendor/toshiba/folio100/proprietary/libomx_wmadec_sharedlibrary.so:system/lib/libomx_wmadec_sharedlibrary.so \
    vendor/toshiba/folio100/proprietary/libomx_wmvdec_sharedlibrary.so:system/lib/libomx_wmvdec_sharedlibrary.so \
    vendor/toshiba/folio100/proprietary/pvplayer.cfg:system/etc/pvplayer.cfg

# Opencore libs for folio100
PRODUCT_COPY_FILES += \
    vendor/toshiba/folio100/proprietary/libopencore_author.so:system/lib/libopencore_author.so \
    vendor/toshiba/folio100/proprietary/libopencore_common.so:system/lib/libopencore_common.so \
    vendor/toshiba/folio100/proprietary/libopencore_downloadreg.so:system/lib/libopencore_downloadreg.so \
    vendor/toshiba/folio100/proprietary/libopencore_download.so:system/lib/libopencore_download.so \
    vendor/toshiba/folio100/proprietary/libopencore_mp4localreg.so:system/lib/libopencore_mp4localreg.so \
    vendor/toshiba/folio100/proprietary/libopencore_mp4local.so:system/lib/libopencore_mp4local.so \
    vendor/toshiba/folio100/proprietary/libopencore_net_support.so:system/lib/libopencore_net_support.so \
    vendor/toshiba/folio100/proprietary/libopencore_player.so:system/lib/libopencore_player.so \
    vendor/toshiba/folio100/proprietary/libopencore_rtspreg.so:system/lib/libopencore_rtspreg.so \
    vendor/toshiba/folio100/proprietary/libopencore_rtsp.so:system/lib/libopencore_rtsp.so

# Stage Fright for folio100
PRODUCT_COPY_FILES += \
   vendor/toshiba/folio100/proprietary/libstagefrighthw.so:system/lib/libstagefrighthw.so
